packaging_format = 2

id = "guacamole"
name = "Guacamole"
description.en = "Clientless remote desktop gateway. It supports standard protocols like VNC, RDP, and SSH."
description.fr = "Service de bureau à distance sans client. Fonctionne avec des protocoles standard comme VNC, RDP, et SSH."

version = "1.4.0~ynh1"

maintainers = ["Jules Bertholet"]

[upstream]
license = "Apache-2.0"
website = "https://guacamole.apache.org/"
admindoc = "https://guacamole.apache.org/doc/gug/"
code = "https://github.com/search?utf8=%E2%9C%93&q=repo%3Aapache%2Fguacamole-server+repo%3Aapache%2Fguacamole-client+repo%3Aapache%2Fguacamole-website&type=Repositories&ref=searchresults"
cpe = "???" # FIXME: optional but recommended if relevant, this is meant to contain the Common Platform Enumeration, which is sort of a standard id for applications defined by the NIST. In particular, Yunohost may use this is in the future to easily track CVE (=security reports) related to apps. The CPE may be obtained by searching here: https://nvd.nist.gov/products/cpe/search. For example, for Nextcloud, the CPE is 'cpe:2.3:a:nextcloud:nextcloud' (no need to include the version number)
fund = "???" # FIXME: optional but recommended (or remove if irrelevant / not applicable). This is meant to be an URL where people can financially support this app, especially when its development is based on volunteers and/or financed by its community. YunoHost may later advertise it in the webadmin.

[integration]
yunohost = ">= 4.1.3"
architectures = "all" # FIXME: can be replaced by a list of supported archs using the dpkg --print-architecture nomenclature (amd64/i386/armhf/arm64), for example: ["amd64", "i386"]
multi_instance = true
ldap = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "sso" key : the "ldap" key corresponds to wether or not a user *can* login on the app using its YunoHost credentials.
sso = "?" # FIXME: replace with true, false, or "not_relevant". Not to confuse with the "ldap" key : the "sso" key corresponds to wether or not a user is *automatically logged-in* on the app when logged-in on the YunoHost portal.
disk = "50M" # FIXME: replace with an **estimate** minimum disk requirement. e.g. 20M, 400M, 1G, ...
ram.build = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...
ram.runtime = "50M" # FIXME: replace with an **estimate** minimum ram requirement. e.g. 50M, 400M, 1G, ...

[install]
    [install.domain]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "domain"

    [install.path]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "path"
    default = "/guacamole"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by Yunohost's core
    type = "user"

    [install.init_main_permission]
    help.en = "Not recommended"
    help.fr = "Pas reccomandé"
    type = "group"
    default = false

[resources]
    [resources.sources]
        [resources.sources.mariadb-java-client]
        url = "https://downloads.mariadb.com/Connectors/java/connector-java-2.7.4/mariadb-java-client-2.7.4.jar"
        sha256 = "f06577b19e89b33028b96cd4f031248e761de7ebc712f4ef535e268df76edb2a"

        [resources.sources.tomcat9_deb]
        url = "http://ftp.debian.org/debian/pool/main/t/tomcat9/tomcat9_9.0.43-2~deb11u3_all.deb"
        sha256 = "c49eaa7de72f8d90f30a8fd9a8ba8e2e4ba51988ce839bb31a4a151758d47206"
        format = "ar"
        rename = "tomcat9.deb"

        [resources.sources.auth-header]
        url = "https://downloads.apache.org/guacamole/1.4.0/binary/guacamole-auth-header-1.4.0.tar.gz"
        sha256 = "3f5491737b3295056949d235120dca60ee9518c951b09271780dddf15166a9de"

        [resources.sources.auth-ldap]
        url = "https://downloads.apache.org/guacamole/1.4.0/binary/guacamole-auth-ldap-1.4.0.tar.gz"
        sha256 = "f28488717b26168a5396e125ec7fbff1b7268a658c6100f6ad1bbfbd18a17779"

        [resources.sources.client]
        url = "https://downloads.apache.org/guacamole/1.4.0/binary/guacamole-1.4.0.war"
        sha256 = "92fb06e3ce8fe4f932ddfdffd75a352c06ab58d3bd0a946faa5beda73e8592f0"
        in_subdir = false

        [resources.sources.server]
        url = "https://downloads.apache.org/guacamole/1.4.0/source/guacamole-server-1.4.0.tar.gz"
        sha256 = "2789075c8b25e5aa42dec505491d3425b7b2fe2051772b0006860c26e8a57b90"

        [resources.sources.auth-jdbc]
        url = "https://downloads.apache.org/guacamole/1.4.0/binary/guacamole-auth-jdbc-1.4.0.tar.gz"
        sha256 = "47f4f121cad74ab64d5baf3d14e8f709677a26b3058005a977277a07716d4d9c"


    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    guacd.default = 4822
    main.default = 8080

    [resources.apt]
    packages = "acl, build-essential, libcairo2, libjpeg62-turbo-dev, libpng-dev, libtool-bin, libossp-uuid-dev, libavcodec-dev, libavformat-dev, libavutil-dev, libswscale-dev, freerdp2-dev, libpango1.0-dev, libssh2-1-dev, libtelnet-dev, libvncserver-dev, libwebsockets-dev, libpulse-dev, libssl-dev, libvorbis-dev, libwebp-dev, tomcat9"

    [resources.database]
    type = "mysql"
